### ISSUE TITLE
Need icons for some subcategories

### ISSUE THREAD

**Issue by CloudNiner** [azavea/mos-greenworks#40]
Subcategories that still need icons in the map filterbar:
- Bike Lanes
- Bike Trails
- New Street Trees
- New Yard Trees

Currently these list items just display a blank circle that is the color of their section

**Comment by ctaylo37** [comment]
How soon do we need these?  End of day or end of week?

**Comment by CloudNiner** [comment]
End of week or early next should be fine.

**Comment by ctaylo37** [comment]
Bike Lanes
https://s3.amazonaws.com/s3.azavea.com/images/gwicons/ic_bike_lane.svg

Bike Trails
https://s3.amazonaws.com/s3.azavea.com/images/gwicons/ic_bike_trail.svg

Street Trees
https://s3.amazonaws.com/s3.azavea.com/images/gwicons/ic_street_tree.svg

Yard Trees
https://s3.amazonaws.com/s3.azavea.com/images/gwicons/ic_yard_tree.svg
