### ISSUE TITLE
Legend scrolling

### ISSUE THREAD

**Issue by jbranigan** [azavea/mos-greenworks#45]
Set up scrolling within legend sections, rather than scrolling section headers out of the way

**Comment by jbranigan** [comment]
Not sure if this is @jfrankl or JEST...

**Comment by jfrankl** [comment]
I can do it!

On Wed, Jun 17, 2015 at 11:53 AM, jbranigan notifications@github.com
wrote:

> Not sure if this is @jfrankl https://github.com/jfrankl or JEST...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/azavea/mos-greenworks/issues/45#issuecomment-112858523
> .

## 

Jeff Frankl, UI/UX Designer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
http://twitter.com
