### ISSUE TITLE
Info window population with only one layer visible

### ISSUE THREAD

**Issue by jbranigan** [azavea/mos-greenworks#47]
Turn off all layers but one. Turn on one layer. Click for info.

The data never populates the info window. Response:

_cdbi_layer_attributes_731154254_1({"errors":["Map 8aec8b71d6899580282efac1cbd72eb4 has no layer number -1"]});

**Comment by CloudNiner** [comment]
I can no longer reproduce this locally or at the staging url. You?

**Comment by CloudNiner** [comment]
Is there a particular layer you turned back on?

**Comment by jbranigan** [comment]
Can't reproduce
